// Generated by CoffeeScript 1.6.1
(function() {
  var Base, block, name, o, _ref;

  Base = require("../php");

  /*
  Helper method used for defining nodes
  */


  o = function(name, toString) {
    return module.exports[name] = toString;
  };

  _ref = Base.Blocks;
  for (name in _ref) {
    block = _ref[name];
    o(name, block);
  }

  /*
  A layout block
  */


  o("layout", function() {
    return "<?php $this->beginContent(" + this.subject + ")?>" + this.body + "<?php $this->endContent(); ?>";
  });

  /*
  A custom block
  */


  o("custom", function() {
    return "<?php ob_start(); ?>" + this.body + "<?php $this->" + this.name + "(" + this.subject + ", ob_get_clean()); ?>";
  });

}).call(this);
