// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = {
    Nodes: require("./nodes"),
    Blocks: require("./blocks"),
    /*
    The default file extension for templates of this type
    */

    extname: ".php",
    /*
    The pattern to use when looking for templates
    */

    pattern: /^template\.html$/,
    /*
    The templates that should be used to wrap the contents
    */

    templates: {
      header: "<?php\n  /**\n   * WARNING: This file has been generated from a template. Changes you make here WILL be overridden.\n   * @view {{id}}\n   * @template {{folder}}/{{name}}{{extname}}\n   *\n   * @var mixed $scope The data scope\n   * @var CController $this The controller\n   */\n?>",
      footer: "",
      combinedHeader: "<?php $this->defineView(\"{id}}\", function($scope) {\nob_start();\n?>",
      combinedFooter: "<?php\nreturn ob_get_clean();\n});?>"
    }
  };

}).call(this);
