// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = {
    "php": require("./php"),
    "php-yii": require("./php-yii"),
    "php-codemix": require("./php-codemix")
  };

}).call(this);
