// Generated by CoffeeScript 1.6.1

/*
Helper method used for defining nodes
*/


(function() {
  var o;

  o = function(name, toString) {
    return module.exports[name] = toString;
  };

  /*
  An `each` block
  */


  o("each", function() {
    return "<?php foreach(" + this.subject + " as $" + this.keyName + " => $" + this.scopeName + "): ?>" + this.body + "<?php endforeach; ?>";
  });

  /*
  An `if` block
  */


  o("if", function() {
    return "<?php if (" + this.subject + "): ?>" + this.body + "<?php endif; ?>";
  });

  /*
  An `unless` block
  */


  o("unless", function() {
    return "<?php if (!(" + this.subject + ")): ?>" + this.body + "<?php endif; ?>";
  });

  /*
  A `with` block
  */


  o("with", function() {
    return "<?php $" + this.scopeName + " = " + this.subject + "; ?>" + this.body;
  });

  /*
  A custom block
  */


  o("custom", function() {
    return "<?php ob_start(); ?>" + this.body + "<?php $this->" + this.name + "(" + this.subject + ", ob_get_clean()); ?>";
  });

}).call(this);
