// Generated by CoffeeScript 1.6.1

/*
# Nodes
The different kinds of node in the AST
*/


(function() {
  var Base, Blocks, name, node, o, _ref;

  Blocks = require("./blocks");

  Base = require("../php");

  /*
  Helper method used for defining nodes
  */


  o = function(name, toString) {
    return module.exports[name] = toString;
  };

  _ref = Base.Nodes;
  for (name in _ref) {
    node = _ref[name];
    o(name, node);
  }

  o("partial", function() {
    return "<?=$this->renderPartial(\"" + this.name + "\", $" + this.scopeName + ")?>";
  });

  o("quotedExpression", function() {
    return "<?=CHtml::encode(" + this.body + ")?>";
  });

  o("block", function() {
    if (Blocks[this.name] != null) {
      return Blocks[this.name].call(this);
    } else {
      return Blocks.custom.call(this);
    }
  });

}).call(this);
